using System;
using Olive.Entities;

namespace Olive.Email
{
    public interface ICustomReplyToEmailQueueItem : IEmailQueueItem
    {
        string ReplyToAddress { get; set; }
        string ReplyToName { get; set; }
    }

    /// <summary>
    /// Represents an email generated by the application.
    /// </summary>
    [LogEvents(false), CacheObjects(false)]
    public interface IEmailQueueItem : IEntity
    {
        /// <summary>
        /// Gets or sets the body of this email.
        /// </summary>
        string Body { get; set; }

        /// <summary>
        /// Gets or sets the Date of this email.
        /// </summary>
        DateTime Date { get; set; }

        /// <summary>
        /// Gets or sets whether SSL is enabled.
        /// </summary>
        bool EnableSsl { get; set; }

        /// <summary>
        /// Gets or sets whether this email is HTML.
        /// </summary>
        bool Html { get; set; }

        /// <summary>
        /// Gets or sets the Sender Address of this email.
        /// </summary>
        string SenderAddress { get; set; }

        /// <summary>
        /// Gets or sets the Sender Name for this email.
        /// </summary>
        string SenderName { get; set; }

        /// <summary>
        /// Gets or sets the Subject of this email.
        /// </summary>
        string Subject { get; set; }

        /// <summary>
        /// Gets or sets the recipient of this email.
        /// </summary>
        string To { get; set; }

        /// <summary>
        /// Gets or sets the Attachments information for this email.
        /// </summary>
        string Attachments { get; set; }

        /// <summary>
        /// Gets or sets the Bcc recipients of this email.
        /// </summary>
        string Bcc { get; set; }

        /// <summary>
        /// Gets or sets the Bcc recipients of this email.
        /// </summary>
        string Cc { get; set; }

        /// <summary>
        /// Gets or sets the number of times sending this email has been tried.
        /// </summary>
        int Retries { get; set; }

        /// <summary>
        /// Gets or sets the VCalendar View of this email.
        /// </summary>
        string VCalendarView { get; set; }

        /// <summary>
        /// Gets or sets the Username to use for sending this email.
        /// </summary>
        string Username { get; set; }

        /// <summary>
        /// Gets or sets the Password to use for sending this email.
        /// </summary>
        string Password { get; set; }

        /// <summary>
        /// Gets or sets the Smtp host address to use for sending this email.
        /// </summary>
        string SmtpHost { get; set; }

        /// <summary>
        /// Gets or sets the Smtp port to use for sending this email.
        /// </summary>
        int? SmtpPort { get; set; }

        /// <summary>
        /// Gets or sets the Category for sending this email.
        /// </summary>
        string Category { get; set; }
    }
}